### ISSUE TITLE
Regex function should support Matcher.find behaviour

### ISSUE THREAD

**Issue by alpha-centauri** [Graylog2/graylog-plugin-pipeline-processor#39] opened 2016-06-21 08:42 UTC
The regex function is implemented with recourse to Java's Matcher.matches method, which means it returns true only if the whole string (i.e. from beginning to end) matches. It should support searching for substrings as with the method Matcher.find.

This is better for performance reasons in case you are only interested in some part of a message, e.g. the timestamp within a Java garbage collector log (because you can define the pattern starting with a line break "\n", followed by the timestamp pattern, instead of any character ".*").

Maybe you could add an optional parameter so the user can choose the preferred method.

**Comment by kroepke** [comment] 2016-06-21 09:17
duplicate of #35

**Closed by kroepke** 2016-06-21 09:17 UTC
