### ISSUE TITLE
Unicode not supported in Pipeline Simulator

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog-plugin-pipeline-processor#61] opened 2016-07-29 08:54 UTC
### Problem description
Any non-ASCII characters in Raw Message will be replaced with '?'
![image](https://cloud.githubusercontent.com/assets/17475270/17243031/246f9e1c-5583-11e6-8795-f3b7c8faf8d4.png)
![image](https://cloud.githubusercontent.com/assets/17475270/17243036/2c6f710a-5583-11e6-9d89-5071c31f0032.png)

The problem is that it is not display issue.
The simulated message actualy contains '?' and thus won't be processed correclty.

### Environment

* Graylog Version: 2.1.0-beta1
* Pipeline Processor plugin version: 1.1.0-beta1

**Comment by kroepke** [comment] 2016-07-29 11:18
I cannot reproduce this issue:
![screenshot](https://cloud.githubusercontent.com/assets/52014/17246807/bda25146-558e-11e6-839b-0b618e506087.png)
![screenshot](https://cloud.githubusercontent.com/assets/52014/17246820/d587e5b4-558e-11e6-81c0-fcaea653268d.png)

Is there any error in the JavaScript console?
Which browser are you using?
String handling should be all based on Unicode strings at least I'm not aware that we are using byte-level access anywhere (and if so that would be a bug, IMHO)

Thanks!

**Comment by hc4** [comment] 2016-07-29 12:12
When I press Load there is warning in console.
`Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `MessageFields`. See https://fb.me/react-warning-keys for more information.`
But it seems to be unrelated.

No other error seen neither in JS Console nor in graylog logs.

**Comment by hc4** [comment] 2016-07-29 12:16
Also there is some font loading errors logged in JS console:
```

5718e98a1d8ed81386af09f8:1 Failed to decode downloaded font: http://graylog/system/pipelines/simulate/2e90d5152ce92858b62ba053c7b9d2cb.woff
5718e98a1d8ed81386af09f8:1 OTS parsing error: invalid version tag
5718e98a1d8ed81386af09f8:1 Failed to decode downloaded font: http://graylog/system/pipelines/simulate/79515ad0788973c533405f7012dfeccd.woff
5718e98a1d8ed81386af09f8:1 OTS parsing error: invalid version tag
5718e98a1d8ed81386af09f8:1 Failed to decode downloaded font: http://graylog/system/pipelines/simulate/97493d3f11c0a3bd5cbd959f5d19b699.woff2
5718e98a1d8ed81386af09f8:1 OTS parsing error: invalid version tag
5718e98a1d8ed81386af09f8:1 Failed to decode downloaded font: http://graylog/system/pipelines/simulate/f42641eed834f7b97a9499362c6c8855.woff
5718e98a1d8ed81386af09f8:1 OTS parsing error: invalid version tag
5718e98a1d8ed81386af09f8:1 Failed to decode downloaded font: http://graylog/system/pipelines/simulate/97493d3f11c0a3bd5cbd959f5d19b699.woff2
5718e98a1d8ed81386af09f8:1 OTS parsing error: invalid version tag
5718e98a1d8ed81386af09f8:1 Failed to decode downloaded font: http://graylog/system/pipelines/simulate/79515ad0788973c533405f7012dfeccd.woff
5718e98a1d8ed81386af09f8:1 OTS parsing error: invalid version tag
5718e98a1d8ed81386af09f8:1 Failed to decode downloaded font: http://graylog/system/pipelines/simulate/f42641eed834f7b97a9499362c6c8855.woff
5718e98a1d8ed81386af09f8:1 OTS parsing error: invalid version tag
5718e98a1d8ed81386af09f8:1 Failed to decode downloaded font: http://graylog/system/pipelines/simulate/2e90d5152ce92858b62ba053c7b9d2cb.woff
5718e98a1d8ed81386af09f8:1 OTS parsing error: invalid version tag
5718e98a1d8ed81386af09f8:1 Failed to decode downloaded font: http://graylog/system/pipelines/simulate/d9ee23d59d0e0e727b51368b458a0bff.woff
5718e98a1d8ed81386af09f8:1 OTS parsing error: invalid version tag
5718e98a1d8ed81386af09f8:1 Failed to decode downloaded font: http://graylog/system/pipelines/simulate/706450d7bba6374ca02fe167d86685cb.ttf
5718e98a1d8ed81386af09f8:1 OTS parsing error: invalid version tag
```

**Comment by hc4** [comment] 2016-07-29 12:22
Tested with IExplorer 11 - same problem

**Comment by edmundoa** [comment] 2016-07-29 13:27
Both errors you see in the console are known and should not be related to the result in the simulation. Is your browser using Unicode encoding for Graylog? In Chrome or Firefox you can find it in the "View" menu.

**Comment by hc4** [comment] 2016-07-29 14:44
Script receives correct text:
![image](https://cloud.githubusercontent.com/assets/17475270/17252144/2236757c-55b4-11e6-8cef-fcc1c316d76e.png)

**Comment by hc4** [comment] 2016-07-29 14:51
Problem is somewhere in backend.

Parse request content:
```
{
    "message": "тест",
    "remote_address": "1.1.1.1",
    "codec": "raw",
    "configuration": {}
}

```
And response:
```
{
    "message": {
        "fields": {
            "_id": "7f8f04f1-559b-11e6-905d-005056b37533",
            "source": "1.1.1.1",
            "message": "????",
            "timestamp": "2016-07-29T14:48:22.975Z"
        },
        "streams": [],
        "source_input_id": null,
        "filter_out": false,
        "journal_offset": -9223372036854775808,
        "timestamp": "2016-07-29T14:48:22.975Z",
        "source": "1.1.1.1",
        "message": "????",
        "id": "7f8f04f1-559b-11e6-905d-005056b37533",
        "field_names": ["_id", "source", "message", "timestamp"],
        "complete": true,
        "validation_errors": "",
        "fields_entries": [{
            "_id": "7f8f04f1-559b-11e6-905d-005056b37533"
        }, {
            "source": "1.1.1.1"
        }, {
            "message": "????"
        }, {
            "timestamp": "2016-07-29T14:48:22.975Z"
        }],
        "field_count": 4,
        "stream_ids": [],
        "is_source_inet_address": false,
        "inet_address": null
    },
    "index": null
}
```

**Comment by hc4** [comment] 2016-07-29 15:26
It seems the problem is in [MessageResource.java](https://github.com/Graylog2/graylog2-server/blob/2ed9d946c7856241a9e8a5c48f84a46becd1657a/graylog2-server/src/main/java/org/graylog2/rest/resources/messages/MessageResource.java)

In **parse()** method, when raw message string converted to bytes, getBytes() method used, which use default platform encoding, which could be not UTF8 (and it is not in my case, i think)
`final RawMessage rawMessage = new RawMessage(0, new UUID(), Tools.nowUTC(), remoteAddress, request.message().getBytes());`

**Comment by hc4** [comment] 2016-07-29 15:31
Just add option `-Dfile.encoding=UTF8` to graylog init and problem solved

**Comment by kroepke** [comment] 2016-07-29 15:32
Good point, probably easiest to change in the startup scripts etc.
We should still make this a forbidden API and specify the charset directly.

**Comment by kroepke** [comment] 2016-08-03 11:21
fixed by https://github.com/Graylog2/graylog2-server/commit/2ccef59877da10a28f57416827219c828ee3c6fe and https://github.com/Graylog2/graylog2-server/issues/2567

**Closed by kroepke** 2016-08-03 11:21 UTC
